### ISSUE TITLE
Ignored root workspace dependencies?

### ISSUE THREAD

**Issue by JackCA** [Madvinking/yarn-isolate-workspace#16]
In a yarn workspace with "root" dependencies i.e. dependencies that should be included in all projects and are listed in the root package.json and installed with `yarn add -W eslint`, it appears that they are ignored when running `npx yarn-isolate-workspace` on a child workspace.

This appears to correctly resolve sibling dependencies (which is awesome), but I don't think it covers this situation.

Am I misusing this library? Or is there a way to add support for this?

**Comment by Madvinking** [comment]
Hi Jack, 
usually, it is preferd to list only dev dependencies on the root project for tooling, scripts, and stuff and each project should list all the dev and prod dependencies it needs to is package.json in order to build and run.
and by listing it to each workspace u give yarn to manage the root node_modules and keep one version of each dependency.

but of course, there are multiple ways to work with yarn workspaces
and this is absolutely one of them.

i will add another flag (one of many we already have)  to also copy the rook package.json dependencies and dev-dependencies

**Comment by JackCA** [comment]
@Madvinking amazing, nice work!

After opening this issue, I dug into this a lot to find out what the best practices were for this (and it was harder to find than anticipated).

I do agree that it looks like each package should list it's own dependencies, although it's a bit of paradigm shift because I had originally thought that it was one of the *biggest* advantages of yarn workspaces themselves.

Thank you for addressing this for folks like me though!

**Comment by Madvinking** [comment]
@JackCA np 
I'm familiar with the frustration to find best practices to manage yarn workspaces monorepo.
we spend tons of time to find a good flow from development to production managing monorepo.
we are happy to help whenever we can.

just publish the v0.2.2 u can try it out with the flag --include-root-deps
:)

**Comment by AlonMiz** [comment]
@JackCA we use this along with https://www.npmjs.com/package/yarn-one-version-rule
to help us use the same version across all packages in our repo
good luck :)

**Comment by JackCA** [comment]
@AlonMiz nice! I found that too after I dug into this rabbit-hole.

Also found https://github.com/JamieMason/syncpack which seems like it may have some more features.

Thanks for sharing
